spring:
  application:
    name: tc1-api-phto
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_SOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.MySQLDialect'
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
server:
  port: ${SERVER_PORT}

